template: |
  ## Changes
  $CHANGES

name-template: v$RESOLVED_VERSION
version-template: $MAJOR.$MINOR.$PATCH
categories:
  - title: Breaking Changes
    labels: [breaking]
  - title: Features
    labels: [feature, enhancement]
  - title: Fixes
    labels: [bug, fix]
  - title: Documentation
    labels: [docs]
  - title: Chore
    labels: [chore]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
exclude-labels:
  - skip-changelog
