name: Bug report
description: Report a bug or regression
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: dropdown
    id: php
    attributes:
      label: PHP version
      options:
        - 8.2
        - 8.3
        - 8.4
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or stacktrace
      render: shell
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
        - label: I included minimal reproducible code
        - label: I ran `composer test` before filing
